package:
  name: licensee
  version: "9.18.0"
  epoch: 0
  description: TBD
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - ruby3.4-dotenv
      - ruby3.4-octokit
      - ruby3.4-reverse_markdown
      - ruby3.4-rugged
      - ruby3.4-thor
      - ruby-3.4

environment:
  contents:
    packages:
      - build-base
      - ruby-3.4-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/licensee/licensee.git
      tag: v${{package.version}}
      expected-commit: 336495543ee8756eb512a6b4ec6ad763cf890701

  - uses: ruby/build
    with:
      gem: ${{package.name}}

  - uses: ruby/install
    with:
      gem: ${{package.name}}
      version: ${{package.version}}

  - uses: ruby/clean

update:
  enabled: true
  github:
    identifier: licensee/licensee
    strip-prefix: v
    use-tag: true
    tag-filter: v

test:
  pipeline:
    - name: Check if command runs
      runs: |
        licensee --help
